### PR TITLE
Backports

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
Don't merge yet.

Blank screen since 78ae9fc (r5259), I can't fix it, sorry. Only audio working.

### CODE REVIEW

**Comment by andres-asm** [comment]
please if it doesn't work just close the PR so it won't be merged accidentally

**Comment by sergiobenrocha2** [comment]
until r5258 it works @fr500

**Comment by sergiobenrocha2** [comment]
@twinaphex

**Comment by inactive123** [comment]
You give up too quickly.

Right now I am focusing on Zarch, mouse related issues, and improving the UI of RetroArch.

**Pull request closed without merging**
